// Use https://finicky-kickstart.now.sh to generate basic configuration
// Learn more about configuration options: https://github.com/johnste/finicky/wiki/Configuration

/*
module.exports = {
  defaultBrowser: "Safari",
  handlers: [
    {
      // Open google.com and *.google.com urls in Google Chrome
      match: [
        "google.com*", // match google.com urls
        finicky.matchDomains(/.*\.google.com/) // use helper function to match on domain only
      ],
      browser: "Google Chrome"
    }
  ]
}
*/

// Generated by Finicky Kickstart 
// Save as ~/.finicky.js

module.exports = {
  defaultBrowser: "Safari",      
  handlers: [
    {
      match: [
        "*.atlassian.net/*",
        "*.mos-team.ru/*",
        "*127.0.0.1*",
        "*localhost*",
        "*postman*",
        "*linkedin.com*",
        "*taxdome.win*",
        "*taxdome.com*",
        "*appsignal.com*",
        "*aws.amazon.com*",
      ],
      browser: "Google Chrome",
    }
  ],
  options: {
    // Hide the finicky icon from the top bar. Default: false
    hideIcon: true, 
    // Check for update on startup. Default: true
    checkForUpdate: true,
    // Log every request with basic information to console. Default: false
    logRequests: false
  },
}